# Generated by Django 2.0.5 on 2019-12-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=100)),
                ('product_cost', models.IntegerField()),
                ('product_class', models.CharField(max_length=100)),
                ('product_color', models.CharField(max_length=100)),
                ('no_of_products', models.IntegerField()),
                ('mfg_date', models.DateField(max_length=100)),
                ('exp_date', models.DateField(max_length=100)),
                ('customer_name', models.CharField(max_length=100)),
                ('mobile_number', models.BigIntegerField()),
                ('email_id', models.EmailField(max_length=100)),
            ],
        ),
    ]
